spring:
  application:
    name: "ServiceDiscovery"

server:
  port: 8761

# https://cloud.spring.io/spring-cloud-netflix/reference/html/#spring-cloud-eureka-server-standalone-mode
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans"
  info:
    env:
      enabled: "true"

# /actuator/info
info:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    applicationName: ${spring.application.name}